
# {.tabset}

## Setup

```{r}
knitr::opts_chunk$set(cache = TRUE)
```

```{r}
library(tidyverse)
library(leaflet)
library(sf)
library(spdep)
data_dir <- "../clean_data/"
maps_dir <- "../maps/"
```

## EDA & Data Wrangling

```{r}
starbucks <- read_csv(paste0(data_dir, "starbucks.csv")) |>
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
starbucks

provinces <- st_read(paste0(maps_dir, "2019年省级.shp")) |>
  select(ENG_NAME) |>
  rename(Province = ENG_NAME) |>
  filter(!(Province %in% c("Taiwan", "HongKong", "Aomen", "Hainan"))) |>
  mutate(Province = case_when(
    Province == "Xizang" ~ "Tibet",
    Province == "Neimenggu" ~ "Inner Mongolia",
    TRUE ~ Province
  ))
provinces
```

```{r, eval=FALSE}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addCircles(
    data = starbucks,
    color = "darkgreen",
    fillColor = "darkgreen"
  ) |>
  addPolygons(
    data = provinces,
    weight = 1.5,
    color = "#4B4B4B",
    opacity = 1,
    label = provinces$Province
  )
```

```{r}
starbucks_provinces <- st_join(starbucks, provinces, left = FALSE)
starbucks_provinces
```

```{r}
starbucks_count <- starbucks_provinces |>
  st_drop_geometry() |>
  group_by(Province) |>
  summarize(count = n()) |>
  left_join(provinces, by = "Province") |>
  st_as_sf()
```

```{r, eval=FALSE}
starbucks_count_pal <- colorNumeric(
  palette = "viridis",
  domain = starbucks_count$count
)

leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = starbucks_count,
    weight = 1.5,
    color = "#4B4B4B",
    opacity = 1,
    fillOpacity = 0.7,
    fillColor = ~starbucks_count_pal(count),
    label = paste(starbucks_count$Province, starbucks_count$count)
  ) |>
  addLegend(
    pal = starbucks_count_pal,
    values = starbucks_count$count,
    title = "Starbucks Count",
    position = "bottomright"
  )
```

## Areal Analysis {.tabset}

### Preparation

```{r}
centroids <- st_coordinates(st_centroid(st_geometry(starbucks_count)))

queen <- poly2nb(starbucks_count)
plot(
  st_geometry(starbucks_count),
  border = "#4B4B4B",
  main = "Queen"
)
plot(
  queen,
  centroids,
  add = TRUE,
  col = "blue",
  lwd = 2
)
```

```{r}
knn4 <- knn2nb(knearneigh(centroids, k = 4))
plot(
  st_geometry(starbucks_count),
  border = "#4B4B4B",
  main = "KNN"
)
plot(
  knn4,
  centroids,
  add = TRUE,
  col = "darkgreen",
  lwd = 2
)
```

```{r}
knn2 <- knn2nb(knearneigh(centroids, k = 2))
plot(
  st_geometry(starbucks_count),
  border = "#4B4B4B",
  main = "KNN"
)
plot(
  knn2,
  centroids,
  add = TRUE,
  col = "darkgreen",
  lwd = 2
)
```

```{r}
queen_knn_diff <- diffnb(queen, knn4)
plot(
  st_geometry(starbucks_count),
  border = "#4B4B4B",
  main = "Queen KNN Diff"
)
plot(
  queen_knn_diff,
  centroids,
  add = TRUE,
  col = "red",
  lwd = 2
)
```

```{r}
queen_weights_b <- nb2listw(queen, style = "B")
queen_weights_b

queen_weights_w <- nb2listw(queen, style = "W")
queen_weights_w

knn4_weights_b <- nb2listw(knn4, style = "B")
knn4_weights_b

knn4_weights_w <- nb2listw(knn4, style = "W")
knn4_weights_w

knn2_weights_b <- nb2listw(knn2, style = "B")
knn2_weights_b

knn2_weights_w <- nb2listw(knn2, style = "W")
knn2_weights_w
```

### Moran's I Normality

```{r}
moran.test(
  starbucks_count$count,
  queen_weights_b,
  randomisation = FALSE,
  alternative = "two.sided"
)

moran.test(
  starbucks_count$count,
  queen_weights_w,
  randomisation = FALSE,
  alternative = "two.sided"
)

moran.test(
  starbucks_count$count,
  knn4_weights_b,
  randomisation = FALSE,
  alternative = "two.sided"
)

moran.test(
  starbucks_count$count,
  knn4_weights_w,
  randomisation = FALSE,
  alternative = "two.sided"
)

moran.test(
  starbucks_count$count,
  knn2_weights_b,
  randomisation = FALSE,
  alternative = "two.sided"
)

moran.test(
  starbucks_count$count,
  knn2_weights_w,
  randomisation = FALSE,
  alternative = "two.sided"
)
```

### Moran's I MCMC

```{r}
moran.mc(
  starbucks_count$count,
  queen_weights_b,
  nsim = 999,
  alternative = "two.sided"
)

moran.mc(
  starbucks_count$count,
  queen_weights_w,
  nsim = 999,
  alternative = "two.sided"
)

moran.mc(
  starbucks_count$count,
  knn4_weights_b,
  nsim = 999,
  alternative = "two.sided"
)

moran.mc(
  starbucks_count$count,
  knn4_weights_w,
  nsim = 999,
  alternative = "two.sided"
)

moran.mc(
  starbucks_count$count,
  knn2_weights_b,
  nsim = 999,
  alternative = "two.sided"
)

moran.mc(
  starbucks_count$count,
  knn2_weights_w,
  nsim = 999,
  alternative = "two.sided"
)
```

### Correlogram

```{r}
corr_queen <- sp.correlogram(
  queen,
  starbucks_count$count,
  order = 5,
  method = "I",
  style = "W",
  randomisation = FALSE,
  zero.policy = TRUE
)
plot(
  corr_queen,
  main = "Moran's I Correlogram for Queen Lags"
)

corr_knn4 <- sp.correlogram(
  knn4,
  starbucks_count$count,
  order = 7,
  method = "I",
  style = "W",
  randomisation = FALSE,
  zero.policy = TRUE
)
plot(
  corr_knn4,
  main = "Moran's I Correlogram for KNN4 Lags"
)

corr_knn2 <- sp.correlogram(
  knn2,
  starbucks_count$count,
  order = 10,
  method = "I",
  style = "W",
  randomisation = FALSE,
  zero.policy = TRUE
)
plot(
  corr_knn2,
  main = "Moran's I Correlogram for KNN2 Lags"
)
```

### Local Moran's I

```{r}
moran_local <- localmoran(starbucks_count$count, knn2_weights_w)
moran_local
```

```{r}
clusters <- starbucks_count |>
  mutate(
    Ii = moran_local[, 1],
    Z_Ii = moran_local[, 4],
    p_value = moran_local[, 5],
  ) |>
  mutate(cluster = case_when(
    Z_Ii > 0 & count > mean(count) & p_value < 0.05 ~ "High-High",
    Z_Ii > 0 & count < mean(count) & p_value < 0.05 ~ "Low-Low",
    Z_Ii < 0 & count > mean(count) & p_value < 0.05 ~ "High-Low",
    Z_Ii < 0 & count < mean(count) & p_value < 0.05 ~ "Low-High",
    TRUE ~ "Not Significant"
  ))
```

```{r, eval=FALSE}
local_moran_pal <- colorFactor(
  c("red", "blue", "darkgreen", "yellow", "gray"),
  levels = c("High-High", "Low-Low", "High-Low", "Low-High", "Not Significant"),
  ordered = TRUE
)

leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = clusters,
    fillColor = ~local_moran_pal(cluster),
    fillOpacity = 0.25,
    color = "#4B4B4B",
    opacity = 1,
    weight = 1.5,
    label = ~paste0(Province, ": ", cluster)
  ) |>
  addLegend(
    "bottomright",
    pal = local_moran_pal,
    values = clusters$cluster,
    title = "Local Moran's I Cluster",
    opacity = 0.25
  )
```

### Local Getis-Ord G*

```{r}
g_star <- localG(starbucks_count$count, knn2_weights_w)
z_scores <- as.numeric(g_star)

g_star_clusters <- starbucks_count |>
  mutate(cluster = case_when(
    z_scores > 1.645 ~ "High",
    z_scores < -1.645 ~ "Low",
    TRUE ~ "Not Significant"
  ))
```

```{r, eval=FALSE}
g_star_pal <- colorFactor(
  c("blue", "red", "gray"),
  levels = c("Low", "High", "Not Significant")
)

leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = g_star_clusters,
    fillColor = g_star_pal(g_star_clusters$cluster),
    fillOpacity = 0.25,
    color = "#4B4B4B",
    opacity = 1,
    weight = 1.5,
    label = ~paste0(Province, ": ", cluster)
  ) |>
  addLegend(
    "bottomright",
    pal = g_star_pal,
    values = g_star_clusters$cluster,
    title = "Local Getis-Ord G*",
    opacity = 0.25
  )
```